### ISSUE TITLE
Feature: Burp Logfile Parsing

### ISSUE THREAD

**Issue by 0x27** [epinna/tplmap#1]
A nice feature to have would be Burp Proxy logfile parsing and fuzzing, ala sqlmap's "-x" option, having it automatically pull in targets to test from such logfile.

**Comment by epinna** [comment]
That's a nice feature, will be implemented later (a lot of other basic features are missing right now). Thanks for the idea!

**Comment by ChrisFernandez** [comment]
Also will be nice for us that rather use Zaproxy

**Comment by epinna** [comment]
@0x27 did you have any chance to test the amazing @jx6f's integration with Burp? See #27 and let me know if it works for you :)

**Comment by epinna** [comment]
Burp integration is now implemented (see #27 ).
