### ISSUE TITLE
Feature: Use wildcard to indicate injection points that aren't standard GET parameters.

### ISSUE THREAD

**Issue by Macmod** [epinna/tplmap#19]
Similarly to sqlmap, a wildcard could be used to indicate injection points that aren't standard GET parameters.

**Comment by epinna** [comment]
Wildcard in POST request data and headers is already supported.

POST data

```
$ ./tplmap.py -u 'http://localhost:15001/post/mako' --data 'var=ok&inj=*&othervar=1'
```

Headers

```
$ ./tplmap.py -u 'http://localhost:15001/header/mako' --headers 'User-Agent: *' --headers 'X-Agent: *'
```

You can run it against the test python suite.

```
$ cd tests
$ ./run_python_tests.sh
```

**Comment by Macmod** [comment]
Thanks for clarifying, epinna, and the question should be elaborated: is there currently a way to do that _in the URL_, but outside GET parameters? That's the support I meant.

**Comment by epinna** [comment]
Got you. Injection points in the URL are not yet supported, but I'll work on that.
