### ISSUE TITLE
Feature: --cookie argument

### ISSUE THREAD

**Issue by gaurang8492** [epinna/tplmap#20]
I couldn't find any option that could help running an authenticated test using tplmap. Just like sqlmap provides --cookie argument which can be used to set the session cookies and run the authenticated scan, similarly there should be an option in tplmap that can be used to provide the session cookie values.
Alternatively, there should also be an option to parse the file into tplmap (just like -r and -l works in sqlmap), which can allow tplmap to parse the post request with session cookies.

**Comment by epinna** [comment]
I implement --cookie argument, on the meanwhile try using --header option.

```
./tplmap.py --header 'Cookie: SID=SECRET' -u 'http://localhost:15001/reflect_cookieauth/mako?inj=asd*'
```

**Comment by epinna** [comment]
It now supports `--cookie` CLI argument.
