### ISSUE TITLE
--os-cmd: cannot put spaces on commands

### ISSUE THREAD

**Issue by netw0rk42** [epinna/tplmap#23]
hello, been trying to add spaces inside --os-cmd values like, <start regedit.exe> / .. cannot add more than "1 single" line

tried using example: --os-cmd=start regedit.exe
result: -r is not an option...

thank you!

**Comment by netw0rk42** [comment]
not --os-shell sorry little mistake,
--os-cmd=start regedit.exe will result to error

**Comment by jx6f** [comment]
@netw0rk42 
Your command seems not quoted. How about `--os-cmd 'command argument1 argument2'`?

Here is my example:

```sh
$ python2 tplmap.py -u 'http://localhost:15002/eval.php?inj=*' --os-cmd 'cat /etc/hosts | grep localhost'

(snip)

127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
```
