### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by jx6f** [epinna/tplmap#24]
The tplmap test environment is very useful for SSTI vulnerability learning. Everyone can easily get test environment by dockerize.

I already dockerized tplmap test environment. May I send it as a pull request?

**Comment by epinna** [comment]
Go ahead, I'll check your pull request.

**Comment by jx6f** [comment]
Thank you. Please check https://github.com/epinna/tplmap/pull/25.

**Comment by epinna** [comment]
Amazing job, looking forward for other contributions :)

**Comment by jx6f** [comment]
I'm glad I could contribute to tplmap. Thanks!
