### ISSUE TITLE
--tpl-shell how to

### ISSUE THREAD

**Issue by its0x08** [epinna/tplmap#37]
any idea on how to use the --tpl-shell ?
can u put any how to please?!

**Comment by epinna** [comment]
It allows you to write template code in the injection point, it's there to help me template inspection and debugging, you don't need to use it normally.

**Comment by its0x08** [comment]
obviously thats the only method working with the site 
with Mako engine thats why im asking..
so if u got any list of shell templates that will help pwn the target please add them to the repo because it will be extremly useful if the tool have the capability to inject a webshell like weevely !
thanks!
