### ISSUE TITLE
How to check if specific string is inside the response?

### ISSUE THREAD

**Issue by opt9** [epinna/tplmap#42]
PR #41 solves jinja2 false-negative, but it clovers nunjucks test because nunjucks and jinja2 uses same syntax.

If I change test_render like below
```python
'test_render': '%(n1)s' % {                                                                                        
    'n1' : '[].__class__.__mro__[1].__subclasses__()'                                                              
}, 
```
Response is
![_001](https://user-images.githubusercontent.com/192655/38918463-c0741402-4328-11e8-93b4-16238906cb94.png)

the html source of response is
![_002](https://user-images.githubusercontent.com/192655/38918475-ce24cb8c-4328-11e8-8b8f-0a7958ef5b51.png)

So, I changed test_render_expected like below
```python
'test_render_expected': '%(res)s' % {
    'res' : 'jinja2.environment.Template'
}
```

But, It does not work.
How to solve it?

**Comment by epinna** [comment]
Do you still have this problem after your last pull request?

**Comment by opt9** [comment]
Thanks for clear explanation. :-)

**Comment by epinna** [comment]
Thanks for your contribution!
