### ISSUE TITLE
Tamper/modify payload before execute payload

### ISSUE THREAD

**Issue by rozium** [epinna/tplmap#54]
Hi, just want to know how to tamper or modify the payload
The problem is server will decrypt the request before executed

Example request (for base64)
`tplmap.py -u 'http://domain.target/page?param1={{*}}'`
So instead `{{*}}`, the payload will become `base64.b64encode("{{*}}")`. Thanks!

**Comment by epinna** [comment]
Hello,

You should write your own module to do that. Read the other modules under `plugin/engines/` and `plugin/languages/` and try to create your own.
