### ISSUE TITLE
i have problem 

### ISSUE THREAD

**Issue by shadihh9** [epinna/tplmap#68]
when install  requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
![rtttttttttttttttt](https://user-images.githubusercontent.com/22076930/92323305-4d14bf80-f040-11ea-98de-656cbe7e261e.png)

**Comment by epinna** [comment]
You're using Python3, while tplmap runs on Python2.
