### ISSUE TITLE
pip3 install -r requirements error.

### ISSUE THREAD

**Issue by sakas23** [epinna/tplmap#70]
Hello community,

I have an error when im trying to install requirements.

![Screenshot_3](https://user-images.githubusercontent.com/57067833/96636388-e9abcc00-1325-11eb-9da1-7b3bf45f1f18.png)

I also have a problem installing pyyalm. The output of pip3 install pyyalm is that requirement already satisfied.

In addition, when i type pip3 show pyyalm it says packages not found.

I am a liitle bit confused.

Any help is really appreciated.

**Comment by epinna** [comment]
It requires Python 2.

**Comment by sakas23** [comment]
So its pip2 install or python2 tplmap IP etc...
