### ISSUE TITLE
HOW TO SOLVE THIS ISSUE ?

### ISSUE THREAD

**Issue by d4715** [epinna/tplmap#83]
Hello There,
I just check your tool yesterday via github.com so i download it and install in my kali that time i used this command
sudo pip3 install -r requirements.txt for download all things which are include in requirements.txt .but after run this command i faced some problems regarding wsgiref==0.1.2 I CAN NOT INSTALL IT  SO PLEASE HELP ME TO RESOLVE THIS ISSUE 
just check this .
Desktop/tools/ssti/tplmap# sudo pip3 install -r requirements.txt 
Collecting PyYAML==5.1.2
  Using cached PyYAML-5.1.2.tar.gz (265 kB)
Collecting certifi==2018.10.15
  Using cached certifi-2018.10.15-py2.py3-none-any.whl (146 kB)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (3.0.4)
Collecting idna==2.8
  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)
Collecting requests==2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting urllib3==1.24.1
  Using cached urllib3-1.24.1-py2.py3-none-any.whl (118 kB)
Collecting wsgiref==0.1.2
  Using cached wsgiref-0.1.2.zip (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7us0e_1x/wsgiref/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7us0e_1x/wsgiref/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-njf2u_yv                                                                                      
         cwd: /tmp/pip-install-7us0e_1x/wsgiref/                                                                            
    Complete output (8 lines):                                                                                              
    Traceback (most recent call last):                                                                                      
      File "<string>", line 1, in <module>                                                                                  
      File "/tmp/pip-install-7us0e_1x/wsgiref/setup.py", line 5, in <module>                                                
        import ez_setup                                                                                                     
      File "/tmp/pip-install-7us0e_1x/wsgiref/ez_setup/__init__.py", line 170                                               
        print "Setuptools version",version,"or greater has been installed."                                                 
              ^                                                                                                             
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?                                                                                                             
    ----------------------------------------                                                                                
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

so please tell me how can i solve these issues.

I am waiting for your valuable reply
Thanks,
d4715

**Comment by epinna** [comment]
It only runs on Python 2 while you're using Python 3.

**Comment by d4715** [comment]
Hello There,
Thanks for your valuable response.
so i have to use pytho2 and i have to use these methods
python2 tplmap.py -u "http://127.0.0.1:5000/?scsp=*" --os-cmd="pwd"
python2 tplmap.py -u "
http://192.168.208.136/xvwa/vulnerabilities/ssti/?name=*&submit="
--os-cmd="pwd"
i am waiting for your valuable reply.
Thanks and Regards,
@d4715
