### ISSUE TITLE
Ability to set path as the injection point ?

### ISSUE THREAD

**Issue by adityathebe** [epinna/tplmap#86]
_Pardon me if this is already possible._

From my brief usage of this tool I understand that it uses the **GET query params** or the **POST data params** as the injection point. 

However, is it possible to use the **url path** as the injection point ?

**Comment by ebarti** [comment]
I have just started using this project like 5 mins ago, but I think I was successful at injecting on URLs by using an asterisk where I want to inject:

./tplmap.py -u 'http://blablabla.com/*'
