### ISSUE TITLE
wsigiref-0.1.2.zip Error

### ISSUE THREAD

**Issue by RichCompton** [epinna/tplmap#88]
This pops up everytime I try and install from requirements.txt for some reason. Seems to be missing a single ( in the 37kb file but the program can't run without it. So far I haven't found a workaround

'''
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ro9rvlm6/wsgiref/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ro9rvlm6/wsgiref/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2omdwmu3
         cwd: /tmp/pip-install-ro9rvlm6/wsgiref/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ro9rvlm6/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-install-ro9rvlm6/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

'''

**Comment by epinna** [comment]
Doesn't work on python3.
