### ISSUE TITLE
3 arguments ?

### ISSUE THREAD

**Issue by highertq** [epinna/tplmap#89]
![image](https://user-images.githubusercontent.com/44385387/109604236-243c3580-7b5e-11eb-91a0-031edc556c6b.png)

# ./tplmap.py -u 'http://114.67.246.176:15899/?flag=1'                                         
Traceback (most recent call last):
  File "./tplmap.py", line 2, in <module>
    from utils import cliparser
  File "/home/kali/tplmap/tplmap/utils/cliparser.py", line 163, in <module>
    parser.formatter.format_option_strings = type(parser.formatter.format_option_strings)(_, parser, type(parser))
TypeError: method expected 2 arguments, got 3

**Comment by XZHhengge** [comment]
not support python3, use python2
